### ISSUE TITLE
Munges up lines motds and other lines where spaces matter

### ISSUE THREAD

**Issue by foxiepaws** [schuster/racket-irc#23]
I am writing an IRC client for fun using this and i found that the part that the code strips out all the spaces of the message content .

I think this is related to the string-split on line 135 of irc/main.rkt. where #:trim? should be set to false.

racket-irc spits out:

    "-*- - ### ### ## ## ### ###"
    "-*- - ## ## ## ## ###### ##### #### ###### ## ## ### # ## ## ######"
    "-*- - ## ### ## ## ## ## ## ## ## ## ## ## ### # ## ##"

but it should look like 

     "-*- - ### ###                                               ##  ## ### ###          "
     "-*- -  ##  ## ##   ## ###### #####    ####   ###### ##   ## ###  #  ##  ##  ######  "
     "-*- -  ##     ###  ##   ##  ##   ##  ##  ## ##   ## ##   ##  ### #  ##        ##    "

Thanks!

**Comment by schuster** [comment]
Thanks for the report; I'll fix this soon.
