### ISSUE TITLE
TLS support?

### ISSUE THREAD

**Issue by winny-** [schuster/racket-irc#24]
Hi does racket-irc support TLS? If not, that would be fantastic.

**Comment by schuster** [comment]
No, because as far as I can tell, there's no TLS library for Racket. If you know of one, I'd be glad to add support to racket-irc.

**Comment by winny-** [comment]
Racket's [`openssl`](http://pkg-build.racket-lang.org/doc/openssl/index.html) built-in offers TLS and SSL.

**Comment by schuster** [comment]
Oh, good. I'll try to add that when I get a chance. Or if you or someone else want to add it, pull requests are welcome.

**Comment by schuster** [comment]
Fixed by PR #25
