### ISSUE TITLE
Update the release branch

### ISSUE THREAD

**Issue by Feufochmar** [schuster/racket-irc#28]
When getting this module with raco (raco pkg install irc), the release branch is used by default, not the master branch (see also https://pkgs.racket-lang.org/package/irc ).
The fix in the answers to PING messages is not present when getting the package this way.
If the master branch should be used by default, then the package data should be updated instead.

**Comment by schuster** [comment]
I just changed the package server to point to master. My plan of using that for development and release only for actual releases ended up being too much overhead for a side project like this.

Thanks for the report.
